export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_DEPARTMENTS = 'GET_DEPARTMENT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT ';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT ';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SEARCH_FOR_PRODUCT = 'SEARCH_FOR_PRODUCT';
export const DEPARTMENT_FILTER_PRODUCT = 'DEPARTMENT_FILTER_PRODUCT';
export const PROMOTION_FILTER_PRODUCT = 'PROMOTION_FILTER_PRODUCT';

export const GET_PROMOTIONS = 'GET_PROMOTIONS';
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
